version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: astro_boilerplate
      POSTGRES_PASSWORD: astro_boilerplate
      POSTGRES_DB: astro_boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: astro_boilerplate
      MONGO_INITDB_ROOT_PASSWORD: astro_boilerplate
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
