// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/vendors/reader.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/vendors/reader.go -destination=internal/application/vendors/mocks/mock_reader.go -package=vendorsmock
//

// Package vendorsmock is a generated GoMock package.
package vendorsmock

import (
	context "context"
	reflect "reflect"

	vendors "github.com/astronautsid/astro-boilerplate/internal/application/vendors"
	pagination "github.com/astronautsid/astro-boilerplate/pkg/pagination"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockReader) List(ctx context.Context, filter vendors.ListFilter, page pagination.Pagination) ([]vendors.VendorListItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, page)
	ret0, _ := ret[0].([]vendors.VendorListItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockReaderMockRecorder) List(ctx, filter, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReader)(nil).List), ctx, filter, page)
}
