// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/vendors/audit.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/vendors/audit.go -destination=internal/application/vendors/mocks/mock_audit.go -package=vendorsmock
//

// Package vendorsmock is a generated GoMock package.
package vendorsmock

import (
	context "context"
	reflect "reflect"

	vendors "github.com/mariozul/mini-rate-limiter/internal/application/vendors"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogWriter is a mock of AuditLogWriter interface.
type MockAuditLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogWriterMockRecorder
	isgomock struct{}
}

// MockAuditLogWriterMockRecorder is the mock recorder for MockAuditLogWriter.
type MockAuditLogWriterMockRecorder struct {
	mock *MockAuditLogWriter
}

// NewMockAuditLogWriter creates a new mock instance.
func NewMockAuditLogWriter(ctrl *gomock.Controller) *MockAuditLogWriter {
	mock := &MockAuditLogWriter{ctrl: ctrl}
	mock.recorder = &MockAuditLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogWriter) EXPECT() *MockAuditLogWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockAuditLogWriter) Write(ctx context.Context, entry vendors.AuditLogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockAuditLogWriterMockRecorder) Write(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockAuditLogWriter)(nil).Write), ctx, entry)
}
