// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/vendors/notification.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/vendors/notification.go -destination=internal/application/vendors/mocks/mock_notification.go -package=vendorsmock
//

// Package vendorsmock is a generated GoMock package.
package vendorsmock

import (
	context "context"
	reflect "reflect"

	event "github.com/mariozul/mini-rate-limiter/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendVendorCreated mocks base method.
func (m *MockNotificationService) SendVendorCreated(ctx context.Context, e event.VendorCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVendorCreated", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVendorCreated indicates an expected call of SendVendorCreated.
func (mr *MockNotificationServiceMockRecorder) SendVendorCreated(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVendorCreated", reflect.TypeOf((*MockNotificationService)(nil).SendVendorCreated), ctx, e)
}
