// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/vendors/transaction.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/vendors/transaction.go -destination=internal/application/vendors/mocks/mock_transaction.go -package=vendorsmock
//

// Package vendorsmock is a generated GoMock package.
package vendorsmock

import (
	context "context"
	reflect "reflect"

	vendors "github.com/mariozul/mini-rate-limiter/internal/application/vendors"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTransactionManager) Execute(ctx context.Context, fn func(vendors.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTransactionManagerMockRecorder) Execute(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTransactionManager)(nil).Execute), ctx, fn)
}
